apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: flaskmonster
  labels:
    app: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      volumes:
      - name: flask-storage
        persistentVolumeClaim:
          claimName: pvc
      containers:
      - name: flask
        image: minatoo/k8sweb
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: "/mnt/flaskweb"
          name: flask-storage
        command: ["bin/bash"]
        args: ["/mnt/flaskweb/cmd.sh"]
        env:
        - name: MONSTER
          volume: "monster.flaskmonster.svc.cluster.local:8080"
        nodeSelector:
          type: flaskweb
---
apiVersion: app/v1
kind: Deployment
metadata:
  name: monster
  namespace: flaskmonster
  labels:
    app: monster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monster
    spec:
      containers:
      - name: monster
        image: amouat/dnmonster:1.0
        ports:
        - containerPort: 8080
      nodeSelector:
        type: flaskweb
